### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by ERussel** [tesseract-one/sr25519.swift#4]
Hello! Thank you for such great wrapper! We are considering to contribute and use this implementation instead of our legacy wrapper based on rust bindings for [Fearless Wallet app](https://fearlesswallet.io) but during the research I found the following questions:

1) Looks like the implementation is based on this [repo](https://github.com/TerenceGe/sr25519-donna). Do you know if there any security audit was conducted for this implementation?

2) I noticed that you have replaced the sha2 hash function implementation with your own. Is this related to performance or any security issue?

**Comment by ypopovych** [comment]
Hello. We will have more. We are working on a full Swift substrate client library. This library is a part of it.

Your questions:
1. I don't know about the audit of that library. It works but theoretically can have security issues.
2. Sha2 function moved to another library. It's needed for proper linking (because we have 2 modules in our set of libraries with sha2 dependency)

**Comment by ERussel** [comment]
Thank you for the answers. Yeah, I noticed that you also have Substrate.swift library and it was a big surprise for me because we also are developing the similar [library](https://github.com/soramitsu/fearless-utils-iOS/). Currently I am trying to understand the pros and cons of this two approaches and how we could union our forces.
